#####
# SimplePrefixes Configuration
#
# Please Note:
#   PlaceholderAPI is required, but all configuration options support Placeholders.
#####
#Don't touch unless asked to
debug-level: 0

# Saving Types: PDC, File
saving-type: "file"
default-prefix: "<white>[<gray>Player</gray>]</white> "
